stages:
  - compile
  - test

language: c

compiler:
  - gcc

before_script: cd IsoLib/HM/build/linux && make && cd -

jobs:
  allow_failures:
    - name: "drc_in_isom" 
  include:
    - stage: compile
      name: "All"
      script: cd IsoLib/linux && make
    - stage: compile
      name: "All + external + drc_in_isom"
      script: cd external/Part04-Dynamic_Range_Control/trunk/tools/writeonlybitbuf/make/ && make && cd -
      script: cd external/Part04-Dynamic_Range_Control/trunk/tools/readonlybitbuf/make/ && make && cd -
      script: cd external/Part04-Dynamic_Range_Control/trunk/tools/wavIO/make/ && make && cd -
      script: cd external/Part04-Dynamic_Range_Control/trunk/modules/uniDrcModules/uniDrcBitstreamDecoderLib/make/ && make && cd -
      script: cd IsoLib/linux && make && cd -
      script: cd IsoLib/drc_in_isom/linux && make

cache:
  directories:
  - IsoLib/HM/build/linux/app/TAppDecoder/objects/
  - IsoLib/HM/build/linux/app/TAppDecoderAnalyser/objects/
  - IsoLib/HM/build/linux/app/TAppEncoder/objects/
  - IsoLib/HM/build/linux/lib/TAppCommon/objects/
  - IsoLib/HM/build/linux/lib/TLibCommon/objects/
  - IsoLib/HM/build/linux/lib/TLibDecoder/objects/
  - IsoLib/HM/build/linux/lib/TLibDecoderAnalyser/objects/
  - IsoLib/HM/build/linux/lib/TLibEncoder/objects/
  - IsoLib/HM/build/linux/lib/TLibVideoIO/objects/
  - IsoLib/HM/build/linux/utils/annexBbytecount/objects/
  - IsoLib/HM/build/linux/utils/convert_NtoMbit_YCbCr/objects/
